name: CI

# env:
#   NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_STAGING }}

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: npm ci
      # - run: npx playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4

      # - name: check formatting
      #   run: npx nx-cloud record -- nx format:check

      # run build tests and lints
      - run: npx nx run-many -t lint test build

      # - run: npx nx-cloud fix-ci
      #   if: always()
